### ISSUE TITLE
Discord Prefix doesn't change from default ?

### ISSUE THREAD

**Issue by Artiume** [KGT1/jellyfin-discord-music-bot#10]
I haven't tried a fresh bot yet but with my current bot, I can't change the prefix from "?". It still responds to ? even though I've changed it for docker. I'll make a fresh bot and see if it behaves different. Also, two bots in the same channel don't play well together, it might be due to both being stuck with ? prefix.

**Comment by KGT1** [comment]
yes its fixed in the nightly
