### ISSUE TITLE
Bot disconnecting from  voice channel when gives command to play music

### ISSUE THREAD

**Issue by Arturitu12** [KGT1/jellyfin-discord-music-bot#16]
Hello, i just created bot like in readme, im running docker, when i type ?summon nothing happens, wheni use ?play, it joining, but when i type ?play and paste music url, it disconnecting. Please help :(

**Comment by Arturitu12** [comment]
I'm using jellyfin 10.7.2

**Comment by NovaCyntax** [comment]
Attach your logs and we may be able to help you. I remember encountering a similar issue a while back, and I believe it had to do with my configuration. Otherwise this may be related to the newest version of jellyfin.

**Comment by Arturitu12** [comment]
U mean a docker logs? (i using docker like in tutorial)

**Comment by Arturitu12** [comment]
https://pastebin.com/M48Fd1hs

**Comment by KGT1** [comment]
@Arturitu12 the current stable release doesnt work with >10.7 you could try to switch to the latest nightly.(Just add :nightly behind KGT1/jellyfin-discord-music-bot for the docker command)

**Comment by Arturitu12** [comment]
Still same

**Comment by Arturitu12** [comment]
https://pastebin.com/0nHSqpLa

**Comment by KGT1** [comment]
do you have your url set right? it has to contain http:// or https://

**Comment by Arturitu12** [comment]
i do

**Comment by Arturitu12** [comment]
let me check

**Comment by Arturitu12** [comment]
It's work now

**Comment by Arturitu12** [comment]
1 thing
