### ISSUE TITLE
Can this be used for any media in jellyfin or only for music?

### ISSUE THREAD

**Issue by ikrowni** [KGT1/jellyfin-discord-music-bot#19]
I would like to be able to start a stream into discord and allow the people watching to control whats playing. Can this be used for that purpose?

**Comment by KGT1** [comment]
If you mean Video Streams:
No, read the README.
You cannot stream video using the Discord API.
You could theoretically create a bot using a user account, but this is against Discords TOS.

**Comment by ikrowni** [comment]
Oh no I meant I wanted to start streaming something on jellyfin to discord using the screen share option then give users the ability to switch episodes or play/pause.

**Comment by KGT1** [comment]
No only thing i can think of is you could stream using mpv shim, everyone logs in with the same user account and controlls you shim client. But this isnt made for that purpose its purely for Audio currently :)
