### ISSUE TITLE
Can't play music

### ISSUE THREAD

**Issue by Metal-666** [KGT1/jellyfin-discord-music-bot#20]
So I added the bot to the server and I can ?summon it to a voice channel, but in Play On menu I can only see my current device, so I can't play anything through the bot. Logs in Jellyfin Dashboard show that the bot is connected to the server. I started the bot from Docker.

**Comment by KGT1** [comment]
If you are on 10.7.x: Try nightly tag. latest isn't on 10.7 yet
otherwise i need more info. set a higher log level and post the logs

**Comment by Metal-666** [comment]
Yep, using nightly tag fixed the problem
Thank you
