### ISSUE TITLE
No Interactive Message Found

### ISSUE THREAD

**Issue by xandau** [KGT1/jellyfin-discord-music-bot#24]
![Imgur](https://i.imgur.com/9N6mqT9.png)

#  No Interactive Message Found

every time i start playing music this error pops up and the bot crashes

any idea what could have gone wrong on my end?

**Comment by KGT1** [comment]
maybe no rights to post in the text channel you are calling it from?

**Comment by alexbcberio** [comment]
I am able to reproduce this issue, permissions are not the problem (at least in my case) as the bot posts correctly a embed saying that it joined the voice channel.
