### ISSUE TITLE
Can't start docker container  

### ISSUE THREAD

**Issue by antoniozh** [KGT1/jellyfin-discord-music-bot#3]
[error.txt](https://github.com/KGT1/jellyfin-discord-music-bot/files/5269513/error.txt)

Hi, I can't start the docker container since it crashes immediately. Do you have any idea what caused it?

**Comment by zadi15** [comment]
Could you post the output of `docker logs <container name>`? It might be helpful in diagnosing the issue

**Comment by KGT1** [comment]
https://www.reddit.com/r/jellyfin/comments/iwszgx/discord_music_bot/g6bvz1x/
