### ISSUE TITLE
Stuck at BitRateTest

### ISSUE THREAD

**Issue by pomigun** [KGT1/jellyfin-discord-music-bot#30]
Hi, it seems that the container is blocked when starting, it is stuck at 
Requesting https://__/Playback/BitrateTest?Size=3000000.
I dunno why, i tested to change the url to my local url but it's blocked earlier on 
Requesting https://__/System/Endpoint.
Maybe i didn't see someting obvious.

**Comment by NovaCyntax** [comment]
Seconded, same issue. Tested virtually every possible variable for an hour, including http and https, as well as deleting discord application/bot, resetting tokens, changing permissions, making admin, etc. It appears as if it's an issue on the discord side of things, as it has no problem signing into Jellyfin and being listed as an active device under the Jellyfin dashboard. I noticed that recently the discord bot API was updated, given the industry's record I wouldn't be surprised if this somehow broke the bot.

**Comment by Stephen-Hamilton-C** [comment]
Also having this issue as well. I haven't tried everything @NovaCyntax has, but even giving the bot admin permissions on my Discord server doesn't work. Here's the full log from the bot:
![Screenshot 2023-04-27 083928](https://user-images.githubusercontent.com/60950821/234864413-99fc2e05-b346-4853-89f2-e38565ac4fce.png)
