### ISSUE TITLE
Stuck at System Endpoint

### ISSUE THREAD

**Issue by thd14** [KGT1/jellyfin-discord-music-bot#32]
Hi,
I tried to set up the bot on Windows, but I get stuck at :
ApiClient serverAddress: http://127.0.0.1:8096
ApiClient appName: Jellyfin Discord Music Bot
ApiClient appVersion: 0.0.1
ApiClient deviceName: [removed]
ApiClient deviceId: [removed]
Requesting url without automatic networking: http://127.0.0.1:8096/Users/authenticatebyname
Requesting http://127.0.0.1:8096/System/Endpoint

My Jellyfin server is running 1.8.7 if it is useful and npn version 8.19.2
I can also see the request and the token on Jellyfin's log
I don't really know how to provide more info.
Tanks

**Comment by Nathan-Moignard** [comment]
I'm having the same issue, could you tell how you fixed it ?

Jellyfin Version: 10.8.8

**Comment by thd14** [comment]
Hi,
Yes, it isn't an issue. Try sending a command to the bot, it should respond.
