### ISSUE TITLE
Music does not play.

### ISSUE THREAD

**Issue by ovingiv** [KGT1/jellyfin-discord-music-bot#34]
So I have the bot running and commands work but music doesn't play at all.
![image](https://user-images.githubusercontent.com/24558152/232416802-be385d82-648e-4aaf-8f6a-06e5f4715ab3.png)
![image](https://user-images.githubusercontent.com/24558152/232416739-69bac533-ed05-46af-83ee-73095fe68bae.png)

**Comment by manuel-rw** [comment]
The project seems to be unmaintained. I rewrote the bot - perhaps you would be interested in that?
