### ISSUE TITLE
Spawn command doesn't reappear

### ISSUE THREAD

**Issue by Artiume** [KGT1/jellyfin-discord-music-bot#8]
I've been able to use the Spawn command but calling for it again doesn't allow it to reappear again.

**Comment by KGT1** [comment]
Can you maybe explain what you mean by this?
Do you want the play message to appear twice?

**Comment by Artiume** [comment]
so the spawn appear is called but it remains whereever we called it in the room. so after a few minutes of talking, we'd have to scroll up and find it. if we try calling for it again, it wont ever appear.

**Comment by Artiume** [comment]
it appears to be working now, I'll keep messing with it to see if i can force the bug to appear.

**Comment by Artiume** [comment]
I think part of my issue was not fully understanding how the websocket and casting played together. Closing a browser window would eventually kill the cast and web socket which would cause the stream to be zombified. Still have spawn not occasionally working.

In other news, I definitely have playlist functionality. I created a playlist and call it and it pulls it. Same for artists. I can call Tool and Metallica, but it didnt find A Perfect Circle.

**Comment by KGT1** [comment]
@Artiume it shouldnt effect the bot at all if you leave the voice channel. whats your setup?

**Comment by Artiume** [comment]
it isn't about leaving or joining voice channels. we'll attempt to ?summon and ?disconnect to try and jog the bot but a lot of times,  it'll ignore any attempt to respond to ?spawn. setup is bot and jf both in docker containers, bridge network, the bot uses jf's internal ip of 172.19.0.6 to communicate, nothing too abnormal.

**Comment by KGT1** [comment]
I think the issue that often the play message didnt appear (as a result of ?spawn or just playing a song with no album cover) was, that the bot didnt gracefully fallback if no Album image was found. I implemented a fallback to the itemId which i dont think is optimal but at least the play message(as a result of ?spawn) appears now.

**Comment by KGT1** [comment]
@Artiume i tested a bit with the latetest nightly and it seems fixed for me. Can you confirm?

**Comment by OdinGitDat** [comment]
I can confirm it works as intended.

**Comment by Artiume** [comment]
all seems good. resolving ticket
